Correção nas funções: cleanup_and_move_files, build_iso, configure_iso_name, set_build_info e md5

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -481,33 +481,40 @@ runs:
         }
 
         configure_kernel() {
-          case "$KERNEL" in
-            oldLts)
-              KERNEL=$(curl -s https://www.kernel.org/feeds/kdist.xml | grep ": longterm" | sed -n 's/.*<title>\(.*\):.*/\1/p' | sort -Vr | sed -n '2s/\.//gp')
-              ;;
-            atualLts)
-              KERNEL=$(curl -s https://www.kernel.org/feeds/kdist.xml | grep ": longterm" | sed -n 's/.*<title>\(.*\):.*/\1/p' | sort -Vr | sed -n '1s/\.//gp')
-              ;;
-            latest)
-              KERNEL=$(curl -s https://raw.githubusercontent.com/biglinux/linux-latest/stable/PKGBUILD | awk -F= '/kernelver=/{print $2}')
-              echo "linux-latest" | sudo tee -a $PROFILE_PATH/$EDITION/Packages-Root
-              ;;
-            xanmod*)
-              echo "linux-firmware" | sudo tee -a $PROFILE_PATH/$EDITION/Packages-Root
-              KERNEL="-${KERNEL}"
-              echo "Configurando kernel xanmod: $KERNEL"
-              ;;
-          esac
-          
-          # Definir KERNEL_NAME
-          if [[ "$KERNEL" != "xanmod" ]]; then
-            KERNEL_NAME="$KERNEL"
-          else
-            local xan_ver
-            xan_ver=$(grep linux-xanmod "$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')" | grep -v headers | cut -d " " -f2 | cut -d "-" -f1 | sed ':a;$!{N;ba;};s/\(.*\)\..*/\1/' | sed 's/\.//')
-            KERNEL_NAME="${KERNEL//-/}${xan_ver}"
-          fi
-          echo "KERNEL_NAME definido como: $KERNEL_NAME"
+            case "$KERNEL" in
+                oldLts)
+                    KERNEL=$(curl -s https://www.kernel.org/feeds/kdist.xml | grep ": longterm" | sed 's/^.*<title>//' | sed 's/<\/title>.*$//' | cut -d ":" -f1 | rev | cut -d "." -f2,3 | rev | head -n2 | sed 's/\.//g' | tail -n1)
+                    ;;
+                atualLts)
+                    KERNEL=$(curl -s https://www.kernel.org/feeds/kdist.xml | grep ": longterm" | sed 's/^.*<title>//' | sed 's/<\/title>.*$//' | cut -d ":" -f1 | rev | cut -d "." -f2,3 | rev | head -n1 | sed 's/\.//g')
+                    ;;
+                latest)
+                    KERNEL=$(curl -s https://raw.githubusercontent.com/biglinux/linux-latest/stable/PKGBUILD | awk -F= '/kernelver=/{print $2}')
+                    echo "linux-latest" >> "$PROFILE_PATH/$EDITION/Packages-Root"
+                    ;;
+                xanmod*)
+                    echo "linux-firmware" >> "$PROFILE_PATH/$EDITION/Packages-Root"
+                    KERNEL="-${KERNEL}"
+                    echo "Configurando kernel xanmod: $KERNEL"
+                    ;;
+            esac
+            
+            # Definir KERNEL_NAME
+            if [[ "$KERNEL" != "xanmod" ]]; then
+                KERNEL_NAME="$KERNEL"
+            else
+                local xan_ver
+                xan_ver=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} + | 
+                          sort -nr | 
+                          awk 'NR==1 {print $2}' | 
+                          xargs grep linux-xanmod | 
+                          grep -v headers | 
+                          awk '{print $2}' | 
+                          cut -d "-" -f1 | 
+                          sed 's/\.//')
+                KERNEL_NAME="${KERNEL//-/}${xan_ver}"
+            fi
+            echo "KERNEL_NAME definido como: $KERNEL_NAME"
         }
 
         configure_repos() {
@@ -566,17 +573,27 @@ runs:
         }
 
         set_build_info() {
-          local release_file="$PROFILE_PATH/$EDITION/root-overlay/etc/big-release"
+            local release_file="$PROFILE_PATH/$EDITION/root-overlay/etc/big-release"
+            local release_dir=$(dirname "$release_file")
 
-          {
-          echo "BUILD_RELEASE=$RELEASE_TAG"
-          echo "BUILD_BRANCH=$BIGBRANCH"
-          echo "UNIX_TIMESTAMP=$(( $(date +%s) / 86400 ))"
-          } >> "$release_file"
+            # Ensure the directory exists
+            mkdir -p "$release_dir"
 
+            {
+                echo "BUILD_RELEASE=$RELEASE_TAG"
+                echo "BUILD_BRANCH=$BIGBRANCH"
+                echo "UNIX_TIMESTAMP=$(( $(date +%s) / 86400 ))"
+                echo "BUILD_DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
+            } > "$release_file"
+
+            echo "Build info written to $release_file"
         }
 
         configure_iso_name() {
+          echo "Debug: DISTRONAME=$DISTRONAME"
+          echo "Debug: MANJAROBRANCH=$MANJAROBRANCH"
+          echo "Debug: COMMUNITYBRANCH=$COMMUNITYBRANCH"
+          
           # Use $DISTRONAME aqui também, em vez de "bigcommunity"
           sed -i "s/label=.*/label=${DISTRONAME}_$RELEASE_TAG.iso/" $PROFILE_PATH/"$EDITION"/profile.conf
           
@@ -588,54 +605,46 @@ runs:
         }
 
         build_iso() {
-          local kernel_name="$KERNEL"
-          
-          if [ "$KERNEL" == "xanmod" ]; then
-            local xan_ver
-            xan_ver=$(grep linux-xanmod "$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')" | grep -v headers | cut -d " " -f2 | cut -d "-" -f1 | sed ':a;$!{N;ba;};s/\(.*\)\..*/\1/' | sed 's/\.//')
-            kernel_name="${KERNEL//-/}${xan_ver}"
-          fi
-          
-          echo "###################################################################"
-          echo "BUILD COMMAND            : buildiso ${SCOPE:+-f} -p community/$EDITION -b $MANJAROBRANCH -k linux${kernel_name} ${OFFICE:+-o}"
-          echo "Building ISO with kernel : linux${kernel_name}"
-          echo "PROFILE_PATH             : $PROFILE_PATH"
-          echo "EDITION                  : $EDITION"
-          echo "MANJAROBRANCH            : $MANJAROBRANCH"
-          echo "KERNEL_NAME              : $kernel_name"
-          echo "SCOPE                    : $SCOPE"
-          echo "OFFICE                   : $OFFICE"
-          echo "###################################################################"
-        
-        # removendo iso-profiles em /usr/share/manjaro-tools/iso-profiles
-          rm -rf /usr/share/manjaro-tools/iso-profiles || true
-          
-          # criando link simbolico para /__w/build-iso/build-iso/iso-profiles
-          ln -sf /__w/build-iso/build-iso/iso-profiles /usr/share/manjaro-tools/iso-profiles || true
-          
-          # habilitando safe.directory
-          git config --global --add safe.directory /usr/share/manjaro-tools/iso-profiles || true
+            echo "###################################################################"
+            echo "BUILD COMMAND            : buildiso ${SCOPE:+-f} -p community/$EDITION -b $MANJAROBRANCH -k linux${KERNEL_NAME} ${OFFICE:+-o}"
+            echo "Building ISO with kernel : linux${KERNEL_NAME}"
+            echo "PROFILE_PATH             : $PROFILE_PATH"
+            echo "EDITION                  : $EDITION"
+            echo "MANJAROBRANCH            : $MANJAROBRANCH"
+            echo "KERNEL_NAME              : $KERNEL_NAME"
+            echo "SCOPE                    : $SCOPE"
+            echo "OFFICE                   : $OFFICE"
+            echo "###################################################################"
 
-          # Query settings and pretend build
-          sudo buildiso -qf || true
-          # END Query settings and pretend build
+            # removendo iso-profiles em /usr/share/manjaro-tools/iso-profiles
+            rm -rf /usr/share/manjaro-tools/iso-profiles || true
+            
+            # criando link simbolico para /__w/build-iso/build-iso/iso-profiles
+            ln -sf /__w/build-iso/build-iso/iso-profiles /usr/share/manjaro-tools/iso-profiles || true
+            
+            # habilitando safe.directory
+            git config --global --add safe.directory /usr/share/manjaro-tools/iso-profiles || true
 
-          sudo buildiso "${SCOPE:+-f}" -p "community/$EDITION" -b "$MANJAROBRANCH" -k "linux${kernel_name}" "${OFFICE:+-o}"
+            # Query settings and pretend build
+            sudo buildiso -qf || true
+            # END Query settings and pretend build
+
+            sudo buildiso "${SCOPE:+-f}" -p "community/$EDITION" -b "$MANJAROBRANCH" -k "linux${KERNEL_NAME}" "${OFFICE:+-o}"
         }
 
         cleanup_and_move_files() {
-          OUTPUT_ISO_PATH_NAME=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
-          FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} \; | sort -nr | awk 'NR==1 {print $2}')
-          echo "ISO_BASENAME=$ISO_BASENAME" >> $GITHUB_ENV  # Exporta WORK_PATH para outras etapas
+            OUTPUT_ISO_PATH_NAME=$(find /var/cache/manjaro-tools/iso -type f -name "*.iso" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+            FILE_PKG=$(find /var/cache/manjaro-tools/iso -type f -name "*-pkgs.txt" -exec stat -c '%Y %n' {} + | sort -nr | awk 'NR==1 {print $2}')
+            
+            echo "ISO_BASENAME=$ISO_BASENAME" >> "$GITHUB_ENV"  # Exporta ISO_BASENAME para outras etapas
 
-          echo "ISO_BASENAME=$ISO_BASENAME"
-          echo "FILE_PKG=$FILE_PKG"
+            echo "ISO_BASENAME=$ISO_BASENAME"
+            echo "FILE_PKG=$FILE_PKG"
 
-          #rm -rf /var/lib/manjaro-tools/buildiso/*
-          mv -fv "$OUTPUT_ISO_PATH_NAME" "$WORK_PATH/$ISO_BASENAME" || true
-          echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_OUTPUT"
-          
-          mv -fv "$FILE_PKG" "$WORK_PATH/${ISO_BASENAME}.pkgs" || true
+            mv -fv "$OUTPUT_ISO_PATH_NAME" "$WORK_PATH/$ISO_BASENAME" || echo "Failed to move ISO file"
+            echo "iso_path=$WORK_PATH/$ISO_BASENAME" >> "$GITHUB_OUTPUT"
+            
+            mv -fv "$FILE_PKG" "$WORK_PATH/${ISO_BASENAME}.pkgs" || echo "Failed to move pkgs file"
         }
 
         main() {
@@ -660,7 +669,7 @@ runs:
           rm -rf iso-profiles/custom-profiles
 
           echo
-          echo "Kernel            : $kernel_name"
+          echo "Kernel            : $KERNEL_NAME"
           echo "Edition           : $EDITION"
           echo "ManjaroBranch     : $MANJAROBRANCH"
           echo "CommunityBranch   : $COMMUNITYBRANCH"
@@ -679,12 +688,15 @@ runs:
       run: |
         echo "Calculating MD5 hash for ISO file..."
         ISO_PATH="${{ steps.build.outputs.iso_path }}"
-
-        # Calculate MD5 hash
-        md5sum "$ISO_PATH" > "${ISO_PATH}.md5"
-
-        echo "MD5 hash calculated and saved:"
-        cat "${ISO_PATH}.md5"
+        
+        if [ -f "$ISO_PATH" ]; then
+          md5sum "$ISO_PATH" > "${ISO_PATH}.md5"
+          echo "MD5 hash calculated and saved:"
+          cat "${ISO_PATH}.md5"
+        else
+          echo "Error: ISO file not found at $ISO_PATH"
+          exit 1
+        fi
 
     - name: Prepare ISO for release
       id: prepare-iso
