Configuração da função manjaro-tools

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -244,10 +244,9 @@ runs:
         REPO="${{ inputs.iso_profiles_repo }}"
         BRANCH="${{ inputs.iso_profiles_branch }}"
         
-        if [ -n "$BRANCH" ]; then
-          sudo git clone --branch "$BRANCH" --depth 1 "$REPO" iso-profiles
-        else
-          sudo git clone --depth 1 "$REPO" iso-profiles
+        if ! sudo git clone ${BRANCH:+--branch "${BRANCH}"} --depth 1 "$REPO" iso-profiles; then
+          echo "Failed to clone ISO profiles repository."
+          exit 1
         fi
         
         echo "ISO profiles cloned successfully."
@@ -329,24 +328,82 @@ runs:
         fi
         
         setup_manjaro_tools() {
+          echo "Setting up Manjaro tools..."
+
+          # Criar e configurar diretórios
           sudo mkdir -p /var/cache/manjaro-tools/iso
           sudo chmod 777 /var/cache/manjaro-tools/iso
-          
-          # Check if buildiso is available
+
+          # Verificar se buildiso está disponível
           if ! command -v buildiso &> /dev/null; then
-            echo "Error: buildiso command not found. Please ensure manjaro-tools-iso is installed correctly."
-            exit 1
+              echo "Error: buildiso command not found. Please ensure manjaro-tools-iso is installed correctly."
+              exit 1
           fi
-          
-          # Check if the profile directory exists
+
+          # Verificar se o diretório do perfil existe
           if [ ! -d "$PROFILE_PATH/$EDITION" ]; then
-            echo "Error: Profile directory $PROFILE_PATH/$EDITION does not exist."
-            exit 1
+              echo "Error: Profile directory $PROFILE_PATH/$EDITION does not exist."
+              exit 1
           fi
-          
-          echo "Manjaro tools setup completed. Directory contents:"
+
+          # Configurar o nome da distribuição e ISO
+          sudo sed -i 's|dist_name=\$(get_distname)|dist_name=BigCommunity|g' /usr/lib/manjaro-tools/util.sh
+          sudo sed -i 's|iso_name=\$(get_osid)|iso_name=bigcommunity|g' /usr/lib/manjaro-tools/util.sh
+
+          # Configurar a marca do BigLinux
+          sudo sed -i -e 's|dist_branding=.*|dist_branding="biglinux"|' /usr/lib/manjaro-tools/util.sh
+
+          # Modificar o nome do arquivo ISO
+          sudo sed -i 's|_${profile}${_edition}_${dist_release//.}|-live|' /usr/lib/manjaro-tools/util-iso.sh
+
+          # Modificar a busca por versões de kernel
+          sudo sed -i '/_kernver=/s/_kernver=.*/_kernver=$(find $1\/usr\/lib\/modules\/ -type f -name version -exec cat {} +)/' /usr/lib/manjaro-tools/util-iso-boot.sh
+
+          # Desabilitar a verificação de versão do kernel
+          sudo sed -i '/${iso_kernel}/s/^/#/' /usr/lib/manjaro-tools/util-iso.sh
+
+          # Configurar o caminho do perfil ISO
+          sudo sed -i "s|^iso_profile=.*|iso_profile=\"$PROFILE_PATH\"|" /etc/manjaro-tools/manjaro-tools.conf
+
+          # Adicionar limpezas do BigLinux
+          add_biglinux_cleanups
+
+          # Adicionar root-overlay
+          sudo sed -i '/copy_overlay "${profile_dir}\/root-overlay" "${path}"/a [[ -e ${profile_dir}\/root-overlay ]] && copy_overlay "${profile_dir}\/root-overlay" "${path}"' /usr/lib/manjaro-tools/util-iso.sh
+
+          # Habilitar plymouth e kms
+          sudo sed -i "s|keyboard keymap|keyboard keymap kms plymouth|g" /usr/share/manjaro-tools/mkinitcpio.conf
+
+          echo "Manjaro tools setup completed. Directory contents of /var/cache/manjaro-tools/iso:"
           ls -la /var/cache/manjaro-tools/iso
-        }
+      }
+
+      add_big_cleanups() {
+          local cleanup_script="/usr/lib/manjaro-tools/util-iso-image.sh"
+          sudo tee -a "$cleanup_script" > /dev/null << EOL
+          # Big cleanups
+          clean_bigfiles() {
+              local path=\$1
+              # Remove documentation
+              rm -rf "\$path/usr/share/doc"/* 2> /dev/null
+              # Remove man pages
+              rm -rf "\$path/usr/share/man"/* 2> /dev/null
+              # Clean LibreOffice configs
+              local libreoffice_path="\$path/usr/lib/libreoffice/share/config"
+              if [[ -d "\$libreoffice_path" ]]; then
+                  rm -f "\$libreoffice_path"/images_{karasa_jaga,elementary,sukapura}* 2> /dev/null
+                  rm -f "\$libreoffice_path"/images_{colibre,sifr_dark,sifr,breeze_dark,breeze}_svg.zip 2> /dev/null
+              fi
+              # Clean wallpapers
+              local wallpapers_path="\$path/usr/share/wallpapers"
+              if [[ -d "\$wallpapers_path" ]]; then
+                  rm -rf "\$wallpapers_path"/{Altai,BytheWater,Cascade,ColdRipple,DarkestHour,EveningGlow,Flow,FlyingKonqui,IceCold,Kokkini,Next,Opal,Patak,SafeLanding,summer_1am,Autumn,Canopee,Cluster,ColorfulCups,Elarun,FallenLeaf,Fluent,Grey,Kite,MilkyWay,OneStandsOut,PastelHills,Path,Shell,Volna}
+              fi
+          }
+      # Call the cleanup function
+      clean_bigfiles "\$1"
+      EOL
+      }
         
         configure_mesa() {
           if [[ "$KERNEL" =~ ^(latest|xanmod)$ ]]; then
@@ -444,9 +501,12 @@ runs:
           
           echo "Building ISO with kernel: linux${kernel_name}"
           echo "PROFILE_PATH = $PROFILE_PATH"
-          cd $PROFILE_PATH
-          pwd
-          sudo buildiso ${SCOPE:+-f} -p "$EDITION" -b "$MANJAROBRANCH" -k "linux${KERNEL_NAME}" ${OFFICE:+-o}
+          echo "EDITION: $EDITION"
+          echo "MANJAROBRANCH: $MANJAROBRANCH"
+          echo "KERNEL_NAME: $kernel_name"
+          echo "SCOPE: $SCOPE"
+          echo "OFFICE: $OFFICE"
+          sudo buildiso ${SCOPE:+-f} -p "$EDITION" -b "$MANJAROBRANCH" -k "linux${kernel_name}" ${OFFICE:+-o}
         }
         
         cleanup_and_move_files() {
@@ -482,7 +542,7 @@ runs:
           
           sudo rm -rf iso-profiles/custom-profiles
           
-          echo "Kernel: $KERNEL_NAME"
+          echo "Kernel: $kernel_name"
           echo "Edition: $EDITION"
           echo "ManjaroBranch: $MANJAROBRANCH"
           echo "CommunityBranch: $COMMUNITYBRANCH"
