Correções do 'install-arch-install-scripts', chacagem na descompactação

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -248,22 +248,31 @@ runs:
         # Find the latest stable version of arch-install-scripts
         VERSION=$(curl -s https://api.github.com/repos/archlinux/arch-install-scripts/tags | grep -oP '"name": "\Kv[0-9.]+(?=")' | sort -V | tail -n1 | cut -c 2-)
         echo "Downloading arch-install-scripts version $VERSION"
-        sudo wget https://gitlab.archlinux.org/archlinux/arch-install-scripts/-/archive/v${VERSION}/arch-install-scripts-v${VERSION}.tar.gz
-        SHA256SUMS=($(curl -s https://gitlab.archlinux.org/archlinux/arch-install-scripts/-/commits/v${VERSION} | grep 'commit' | awk '{print $2}'))
-        for sum in "${SHA256SUMS[@]}"; do
-          echo "${sum} arch-install-scripts-v${VERSION}.tar.gz" | sha256sum --check && break
-        done || exit 1
 
-        sudo tar -xvf arch-install-scripts-v${VERSION}.tar.gz
+        # Try to download and extract the archive up to 3 times
+        MAX_ATTEMPTS=3
+        ATTEMPT=1
+        while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
+          sudo wget -O arch-install-scripts.tar.gz https://gitlab.archlinux.org/archlinux/arch-install-scripts/-/archive/v${VERSION}/arch-install-scripts-v${VERSION}.tar.gz
+          sudo tar -xvf arch-install-scripts.tar.gz && break  # Exit loop if extraction succeeds
+          echo "Attempt $ATTEMPT failed. Trying again..."
+          sudo rm -f arch-install-scripts.tar.gz
+          ATTEMPT=$((ATTEMPT+1))
+        done
+
+        # Check if the extraction was successful after all attempts
+        if [ $ATTEMPT -gt $MAX_ATTEMPTS ]; then
+          echo "Failed to download and extract arch-install-scripts after $MAX_ATTEMPTS attempts."
+          exit 1
+        fi
+
         sudo make -C arch-install-scripts-v${VERSION} || exit 1
         sudo make -C arch-install-scripts-v${VERSION} check || exit 1
         sudo make -C arch-install-scripts-v${VERSION} PREFIX=/usr install || exit 1
 
         sudo touch /etc/pacman-mirrors.conf
 
-        sudo rm arch-install-scripts-v${VERSION}.tar.gz
-        sudo rm -r arch-install-scripts-v${VERSION}
-
+        sudo rm -rf arch-install-scripts-v${VERSION} arch-install-scripts.tar.gz
 
     - id: install-calamares-tools
       shell: bash
