correção para o caminho do profile

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -304,14 +304,21 @@ runs:
         OFFICE: ${{ inputs.office-chooser }}
         RELEASE_TAG: ${{ inputs.release_tag }}
       run: |
+        PROFILE_PATH="community"
         setup_manjaro_tools() {
           sudo mkdir -p /var/cache/manjaro-tools/iso
           sudo chmod 777 /var/cache/manjaro-tools/iso
           
-          # Verifique se buildiso está disponível
+          # Check if buildiso is available
           if ! command -v buildiso &> /dev/null; then
             echo "Error: buildiso command not found. Please ensure manjaro-tools-iso is installed correctly."
             exit 1
+          fi
+          
+          # Check if the profile directory exists
+          if [ ! -d "/usr/share/manjaro-tools/iso-profiles/${PROFILE_PATH}/$EDITION" ]; then
+              echo "Error: Profile directory /usr/share/manjaro-tools/iso-profiles/${PROFILE_PATH}/$EDITION does not exist."
+              exit 1
           fi
           
           echo "Manjaro tools setup completed. Directory contents:"
@@ -320,8 +327,8 @@ runs:
         
         configure_mesa() {
           if [[ "$KERNEL" =~ ^(latest|xanmod)$ ]]; then
-            echo -e "mesa-tkg-stable\nlib32-mesa-tkg-stable" | sudo tee -a iso-profiles/community/$EDITION/Packages-Root
-            sudo sed -i '/libva-mesa/d; /vulkan-swrast/d' iso-profiles/community/$EDITION/Packages-{Desktop,Mhwd}
+              echo -e "mesa-tkg-stable\nlib32-mesa-tkg-stable" | sudo tee -a iso-profiles/${PROFILE_PATH}/$EDITION/Packages-Root
+              sudo sed -i '/libva-mesa/d; /vulkan-swrast/d' iso-profiles/${PROFILE_PATH}/$EDITION/Packages-{Desktop,Mhwd}
           fi
         }
         
@@ -335,10 +342,10 @@ runs:
               ;;
             latest)
               KERNEL=$(curl -s https://raw.githubusercontent.com/biglinux/linux-latest/stable/PKGBUILD | awk -F= '/kernelver=/{print $2}')
-              echo "linux-latest" | sudo tee -a iso-profiles/community/$EDITION/Packages-Root
+              echo "linux-latest" | sudo tee -a iso-profiles/${PROFILE_PATH}/$EDITION/Packages-Root
               ;;
             xanmod*)
-              echo "linux-firmware" | sudo tee -a iso-profiles/community/$EDITION/Packages-Root
+              echo "linux-firmware" | sudo tee -a iso-profiles/${PROFILE_PATH}/$EDITION/Packages-Root
               KERNEL="-${KERNEL}"
               ;;
           esac
@@ -373,13 +380,13 @@ runs:
         }
         
         set_build_info() {
-          echo "BUILD_RELEASE=$RELEASE_TAG" | sudo tee -a iso-profiles/community/"$EDITION"/root-overlay/etc/big-release
-          echo "BUILD_BRANCH=$BIGBRANCH" | sudo tee -a iso-profiles/community/"$EDITION"/root-overlay/etc/big-release
-          echo "UNIX_TIMESTAMP=$(( $(date +%s) / 86400 ))" | sudo tee -a iso-profiles/community/"$EDITION"/root-overlay/etc/big-release
+          echo "BUILD_RELEASE=$RELEASE_TAG" | sudo tee -a iso-profiles/${PROFILE_PATH}/"$EDITION"/root-overlay/etc/big-release
+          echo "BUILD_BRANCH=$BIGBRANCH" | sudo tee -a iso-profiles/${PROFILE_PATH}/"$EDITION"/root-overlay/etc/big-release
+          echo "UNIX_TIMESTAMP=$(( $(date +%s) / 86400 ))" | sudo tee -a iso-profiles/${PROFILE_PATH}/"$EDITION"/root-overlay/etc/big-release
         }
         
         configure_iso_name() {
-          sudo sed -i "s/label=.*/label=bigcommunity_$RELEASE_TAG.iso/" iso-profiles/community/"$EDITION"/profile.conf
+          sudo sed -i "s/label=.*/label=bigcommunity_$RELEASE_TAG.iso/" iso-profiles/${PROFILE_PATH}/"$EDITION"/profile.conf
           
           case "$MANJAROBRANCH/$COMMUNITYBRANCH" in
             stable/stable) TARGET_ISO_PATH="${NAME}_STABLE_${EDITION}_${RELEASE_TAG%%_*}_k${KERNEL}.iso" ;;
@@ -401,10 +408,10 @@ runs:
           
           echo "Current directory: $(pwd)"
           echo "Manjaro tools version: $(pacman -Q manjaro-tools-iso-git)"
-          echo "Build command: buildiso ${SCOPE:+-f} -p \"$EDITION\" -b \"$MANJAROBRANCH\" -k \"linux${kernel_name}\" ${OFFICE:+-o}"
+          echo "Build command: buildiso ${SCOPE:+-f} -p \"${PROFILE_PATH}/$EDITION\" -b \"$MANJAROBRANCH\" -k \"linux${kernel_name}\" ${OFFICE:+-o}"
           
           echo "Building ISO with kernel: linux${kernel_name}"
-          sudo buildiso ${SCOPE:+-f} -p "$EDITION" -b "$MANJAROBRANCH" -k "linux${kernel_name}" ${OFFICE:+-o}
+          sudo buildiso ${SCOPE:+-f} -p "${PROFILE_PATH}/$EDITION" -b "$MANJAROBRANCH" -k "linux${kernel_name}" ${OFFICE:+-o}
         }
         
         cleanup_and_move_files() {
@@ -426,7 +433,8 @@ runs:
           configure_kernel
           
           for config in user-repos.conf live-overlay/etc/pacman.conf root-overlay/etc/pacman.conf; do
-            configure_repos "iso-profiles/community/$EDITION/$config" "$COMMUNITYBRANCH" "$BIGBRANCH"
+            echo "Configuring $config..."
+            configure_repos "iso-profiles/${PROFILE_PATH}/$EDITION/$config" "$COMMUNITYBRANCH" "$BIGBRANCH"
           done
           
           set_build_info
@@ -439,6 +447,7 @@ runs:
           echo "ManjaroBranch: $MANJAROBRANCH"
           echo "CommunityBranch: $COMMUNITYBRANCH"
           echo "BigLinuxBranch: $BIGBRANCH"
+          echo "ISO profiles path: /usr/share/manjaro-tools/iso-profiles/${PROFILE_PATH}/$EDITION"
           
           build_iso
           cleanup_and_move_files
